name: Manual trigger con report
on:
  workflow_dispatch:
  repository_dispatch:
    types: [dependency_update]

jobs:
  cypress-chrome-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 22.6.0

      - name: Instalar dependencias
        run: npm install

      - name: Instalar Cypress
        run: npm install cypress --save-dev

      - name: Instalar Mochawesome
        run: npm install mochawesome mochawesome-merge mochawesome-report-generator --save-dev

      - name: Lanzar pruebas
        run: npx cypress run --reporter mochawesome --reporter-options reportDir=cypress/reports,reportFilename=report

      - name: Generar reporte HTML
        run: npx mochawesome-merge cypress/reports/*.json | npx mochawesome-report-generator

      - name: Publicar reporte en GitHub Pages
        if: github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/mochawesome-report
